CREATE TABLE Tournaments(
	TournamentId SERIAL PRIMARY KEY,
	TournamentName VARCHAR(100) NOT NULL,
	WinnerTeamId INT NULL,
	YearOfMaintenance INT NOT NULL CHECK(YearOfMaintenance >=1850),
	PlaceOfMaintenance VARCHAR(100),
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Matches(
	MatchId SERIAL PRIMARY KEY,
	MatchTypeId INT NOT NULL,
	RefereeId INT NOT NULL,
	TournamentId INT NOT NULL,
	HomeTeamId INT NOT NULL,
	AwayTeamId INT NOT NULL,
	Date DATE DEFAULT CURRENT_DATE,
	Time TIME DEFAULT CURRENT_TIME,
	HomeScore INT DEFAULT 0,
	AwayScore INT DEFAULT 0,
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Teams(
	TeamId SERIAL PRIMARY KEY,
	TeamName VARCHAR(100) NOT NULL,
	Country VARCHAR(100) NOT NULL,
	Representative VARCHAR(100) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	Contact VARCHAR(30) NOT NULL,
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Referees(
	RefereeId SERIAL PRIMARY KEY,
	RefereeFirstName VARCHAR(100) NOT NULL,
	RefereeLastName VARCHAR(100) NOT NULL,
	Nationality VARCHAR(100) NOT NULL,
	Contact VARCHAR(30) NOT NULL,
	BirthDate DATE NOT NULL CHECK(BirthDate<CURRENT_DATE),
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE MatchType(
	MatchTypeId SERIAL PRIMARY KEY,
	MatchTypeName VARCHAR(100) NOT NULL,
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Events(
	EventId SERIAL PRIMARY KEY,
	PlayerId INT NOT NULL,
	MatchId INT NOT NULL,
	EventType VARCHAR(100) NOT NULL,
	MinutesOfEvent INT NOT NULL CHECK(MinutesOfEvent>0),
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Players(
	PlayerId SERIAL PRIMARY KEY,
	TeamId INT NOT NULL,
	PlayerFirstName VARCHAR(100) NOT NULL,
	PlayerLastName VARCHAR(100) NOT NULL,
	BirthDate DATE NOT NULL CHECK(BirthDate<CURRENT_DATE),
	ShirtNumber INT CHECK(ShirtNumber>0),
	Position VARCHAR(100) NOT NULL,
	Contact VARCHAR(30) NOT NULL,
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


