CREATE TABLE Tournaments(
	TournamentId SERIAL PRIMARY KEY,
	TournamentName VARCHAR(100) NOT NULL,
	WinnerTeamId INT NULL,
	YearOfMaintenance INT NOT NULL CHECK(YearOfMaintenance >=1850),
	PlaceOfMaintenance VARCHAR(100),
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Matches(
	MatchId SERIAL PRIMARY KEY,
	MatchTypeId INT NOT NULL,
	RefereeId INT NOT NULL,
	TournamentId INT NOT NULL,
	HomeTeamId INT NOT NULL,
	AwayTeamId INT NOT NULL,
	Date DATE DEFAULT CURRENT_DATE,
	Time TIME DEFAULT CURRENT_TIME,
	HomeScore INT DEFAULT 0 CHECK (HomeScore >= 0),
	AwayScore INT DEFAULT 0 CHECK (AwayScore >= 0),
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Teams(
	TeamId SERIAL PRIMARY KEY,
	TeamName VARCHAR(100) NOT NULL,
	Country VARCHAR(100) NOT NULL,
	Representative VARCHAR(100) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	Contact VARCHAR(30) NOT NULL,
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Referees(
	RefereeId SERIAL PRIMARY KEY,
	RefereeFirstName VARCHAR(100) NOT NULL,
	RefereeLastName VARCHAR(100) NOT NULL,
	Nationality VARCHAR(100) NOT NULL,
	Contact VARCHAR(30) NOT NULL,
	BirthDate DATE NOT NULL CHECK(BirthDate<CURRENT_DATE),
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE MatchTypes(
	MatchTypeId SERIAL PRIMARY KEY,
	MatchTypeName VARCHAR(100) NOT NULL,
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Events(
	EventId SERIAL PRIMARY KEY,
	PlayerId INT NOT NULL,
	MatchId INT NOT NULL,
	EventType VARCHAR(100) NOT NULL,
	MinutesOfEvent INT NOT NULL CHECK(MinutesOfEvent>0),
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Players(
	PlayerId SERIAL PRIMARY KEY,
	TeamId INT NOT NULL,
	PlayerFirstName VARCHAR(100) NOT NULL,
	PlayerLastName VARCHAR(100) NOT NULL,
	BirthDate DATE NOT NULL CHECK(BirthDate<CURRENT_DATE),
	ShirtNumber INT CHECK(ShirtNumber>0),
	Position VARCHAR(100) NOT NULL,
	Contact VARCHAR(30) NOT NULL,
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- dodavanje FK
ALTER TABLE Matches
	ADD CONSTRAINT FkMatchesMatchType
	FOREIGN KEY (MatchTypeId) REFERENCES MatchTypes(MatchTypeId),
	ADD CONSTRAINT FkMatchesRefereeId 
	FOREIGN KEY (RefereeId) REFERENCES Referees(RefereeId),
	ADD CONSTRAINT FkMatchesTournamentId
	FOREIGN KEY (TournamentId) REFERENCES Tournaments(TournamentId),
	ADD CONSTRAINT FkMatchesHomeTeam
	FOREIGN KEY (HomeTeamId) REFERENCES Teams(TeamId),
	ADD CONSTRAINT FkMatchesAwayTeam
	FOREIGN KEY (AwayTeamId) REFERENCES Teams(TeamId);

ALTER TABLE Events
	ADD CONSTRAINT FkEventsPlayer
	FOREIGN KEY (PlayerId) REFERENCES Players(PlayerId),
	ADD CONSTRAINT FkEventsMatch
	FOREIGN KEY (MatchId) REFERENCES Matches(MatchId);

ALTER TABLE Players
	ADD CONSTRAINT FkPlayersTeam
	FOREIGN KEY (TeamId) REFERENCES Teams(TeamId);

ALTER TABLE Tournaments
	ADD CONSTRAINT FkTournamentsWinner
	FOREIGN KEY (WinnerTeamId) REFERENCES Teams(TeamId);

-- dodatne tablice za M:N	

CREATE TABLE TournamentsTeams(
	TournamentTeamId SERIAL PRIMARY KEY,
	TournamentId INT REFERENCES Tournaments(TournamentId),
	TeamId INT REFERENCES Teams(TeamId),
	UNIQUE (TournamentId, TeamId),
	Points INT CHECK(Points>= 0),
	ScoredGoals INT CHECK (ScoredGoals >= 0),
	ConcededGoals INT CHECK(ConcededGoals >= 0),
	ReachedStage VARCHAR(100) CHECK(ReachedStage IN ('grupa','šesnaestina','osmina','četvrtfinale','polufinale','finale')),
	Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- dodatni uvjeti
CREATE OR REPLACE FUNCTION SetUpdateEntity()
	RETURNS TRIGGER
AS
$$
	BEGIN
	NEW.Updated_at = CURRENT_TIMESTAMP;
RETURN NEW;
	END;
$$
language plpgsql;


CREATE TRIGGER UpdateTournaments
	BEFORE UPDATE ON Tournaments
	FOR EACH ROW
	EXECUTE FUNCTION SetUpdateEntity();

CREATE TRIGGER UpdateTeams
	BEFORE UPDATE ON Teams
	FOR EACH ROW
	EXECUTE FUNCTION SetUpdateEntity();

CREATE TRIGGER UpdateMatches
	BEFORE UPDATE ON Matches
	FOR EACH ROW
	EXECUTE FUNCTION SetUpdateEntity();

CREATE TRIGGER UpdateReferees
	BEFORE UPDATE ON Referees
	FOR EACH ROW
	EXECUTE FUNCTION SetUpdateEntity();

CREATE TRIGGER UpdateMatchType
	BEFORE UPDATE ON MatchTypes
	FOR EACH ROW
	EXECUTE FUNCTION SetUpdateEntity();

CREATE TRIGGER UpdateEvents
	BEFORE UPDATE ON Events
	FOR EACH ROW
	EXECUTE FUNCTION SetUpdateEntity();

CREATE TRIGGER UpdateTournamentsTeams
	BEFORE UPDATE ON TournamentsTeams
	FOR EACH ROW
	EXECUTE FUNCTION SetUpdateEntity();

CREATE TRIGGER UpdatePlayers
	BEFORE UPDATE ON Players
	FOR EACH ROW
	EXECUTE FUNCTION SetUpdateEntity();













